# A simple workflow to run a manual job
name: Automatic workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Print Commit Hash
        run: |
          echo ${{ github.sha }}
