name: Tag Event Workflow

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Tag Information
        id: tag_info
        run: |
          echo "Tag name: ${{ github.ref_name }}"
          echo "Tag branch: ${{ github.event.before }}"
      
