# A simple workflow to run a manual job
name: Manual workflow

on:
  workflow_dispatch:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Print Commit Hash
        run: |
          echo ${{ github.sha }}
  